Knapsack
guitartsword/analisis-algoritmos pull request #2
Opened 2017-12-07 17:47 UTC by miguepity

No se si tocar CSS, ahi vemos despues

2017-12-10 00:05 UTC, guitartsword approved these changes

2017-12-11 04:23 UTC, guitartsword requested changes
Borra el InformeProyecto.docx de github y subilo a google drive

2017-12-14 03:54 UTC, guitartsword commented on src/Knapsack/knapsack.js
> +    swal("Solucion","Las ganancias maximas es: "+this.knapsack()+ " con objectos: "+item, 'success');
me imprime los objetos repetidos al hacer click en empezar algoritmo varias veces

2017-12-14 03:57 UTC, guitartsword requested changes

2017-12-14 03:57 UTC, guitartsword commented on src/Knapsack/knapsack.js
> +    swal("Solucion","Las ganancias maximas es: "+this.knapsack()+ " con objectos: "+item, 'success');
me imprime los objetos repetidos al hacer click en empezar algoritmo varias veces

2017-12-15 16:43 UTC, miguepity commented
@guitartsword hoy si ya esta completado Knapsack

2017-12-15 17:36 UTC, guitartsword requested changes

2017-12-15 17:36 UTC, guitartsword commented on src/Knapsack/knapsack.js
> +    swal("Solucion",`El tiempo que nos tardamos en poder clacular la maxima ganancias es de: ${endTime-starTime} milisegundos.Las ganancias maximas es: `+this.knapsack()+ "LPS, con objectos: "+item,
siempre muestra 0 ms de tiempo, creo que tenes que usar hacer algo asi:
```javascript
let ganacia = this.knapsack();
swal(`..${endTime-startTime}...${ganancia}...`);
```
porque el `endTime-startTime` se cambia dentro de la funcion knapsack

Tambien trata de no usar concatenacion de strings con ""+""
usa el [template literal
](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

2017-12-15 19:03 UTC, guitartsword approved these changes

2017-12-15 19:03 UTC, merged